package game

import (
	"embed"
	"encoding/json"
	"fmt"
	"io/fs"
	"sort"
)

// Embeds the per-ability catalog tree. Layout mirrors the projectile/effect
// catalogs (one directory per id):
//
//	catalog/abilities/<id>/<id>.json   — AbilityDef for that ability
//
// `all:` is used so the directory can carry a `.keep` placeholder and embed
// cleanly while the catalog is still empty (the first real ability, Heal, is
// authored in a later part). The loader skips non-directory entries, so the
// placeholder is harmless.
//
//go:embed all:catalog/abilities
var abilityDefsFS embed.FS

// AbilityType classifies an ability. Extensible enum (mirrors DamageType):
// new types are added with a const here; "spell" is the one the animation
// system keys on (a "spell" cast plays the unit's casting animation — see
// Part 5 / unit_animation.go).
type AbilityType string

const (
	// AbilitySpell is a magical ability. Casting one drives the unit's
	// "Casting" animation slot (distinct from a basic attack).
	AbilitySpell AbilityType = "spell"
	// AbilityPassive is an ability that is NEVER manually or auto-cast and
	// never occupies the castable action row. Its effect is driven by its own
	// system (e.g. arcane_missiles auto-fires from Arcane Charge — see
	// spell_charge.go). It is still a catalog AbilityDef the unit "knows".
	AbilityPassive AbilityType = "passive"
)

// CastRangeMatchAttackRange is the sentinel value of a CastRange that means
// "mirror the caster's current attack range". Authored in JSON either as the
// number -1 or the string "match_attack_range".
const CastRangeMatchAttackRange = -1.0

// CastRange is an ability's targeting range. It unmarshals from JSON as
// EITHER a number (world-pixel radius) OR the string "match_attack_range"
// (resolves to the caster's AttackRange at use time). Any negative number is
// treated as the match sentinel so authoring -1 also works, per the spec.
type CastRange float64

func (c *CastRange) UnmarshalJSON(b []byte) error {
	if len(b) > 0 && b[0] == '"' {
		var s string
		if err := json.Unmarshal(b, &s); err != nil {
			return err
		}
		if s == "match_attack_range" {
			*c = CastRangeMatchAttackRange
			return nil
		}
		return fmt.Errorf("invalid cast_range %q: only the string \"match_attack_range\" is recognised", s)
	}
	var f float64
	if err := json.Unmarshal(b, &f); err != nil {
		return err
	}
	*c = CastRange(f)
	return nil
}

// MarshalJSON writes the match-attack-range sentinel back as the string
// "match_attack_range" (symmetric with UnmarshalJSON) so an authored ability
// round-trips through SaveAbilityDef without collapsing the sentinel to -1.
// Any concrete range marshals as its plain number.
func (c CastRange) MarshalJSON() ([]byte, error) {
	if c.MatchesAttackRange() {
		return []byte(`"match_attack_range"`), nil
	}
	return json.Marshal(float64(c))
}

// MatchesAttackRange reports whether this cast range mirrors the caster's
// attack range (the -1 / "match_attack_range" sentinel).
func (c CastRange) MatchesAttackRange() bool { return float64(c) < 0 }

// Resolve returns the concrete world-pixel range for a caster: the caster's
// AttackRange when this is the match sentinel, otherwise the literal value.
// A nil caster resolves the match sentinel to 0 (cannot reach anything).
func (c CastRange) Resolve(caster *Unit) float64 {
	if c.MatchesAttackRange() {
		if caster == nil {
			return 0
		}
		return caster.AttackRange
	}
	return float64(c)
}

// AbilityDef is the authoritative, server-owned definition of an activatable
// ability (spell, etc.). New framework (there is no prior ability system);
// it reuses the existing catalog / DamageType / effect-id conventions rather
// than the passive perk system.
//
// Cast/auto-cast *behavior* (cast-time lifecycle, mana spend, the auto-cast
// loop) is built on this def in later parts; this part owns the data model
// plus targeting and cast-range validation.
type AbilityDef struct {
	// ID is the stable identifier (e.g. "heal"); must match the containing
	// directory name when loaded from the catalog.
	ID string `json:"id"`
	// DisplayName is the player-facing name (e.g. "Heal").
	DisplayName string `json:"displayName"`
	// Description is an OPTIONAL author-facing override of the ability's
	// player-facing tooltip prose. Empty (the default) ⇒ the tooltip / editor
	// preview render the text generated by describeAbility() from the ability's
	// configured fields; non-empty ⇒ this verbatim string wins. It lets an
	// author correct generated prose that reads wrong for an unusual config,
	// without the generator having to model every phrasing. Use
	// EffectiveDescription() to resolve override-else-generated in one call.
	Description string `json:"description,omitempty"`
	// Type classifies the ability. "spell" drives the casting animation.
	// NOTE: `type` is not in the Part 6 attribute bullet list but is required
	// by the animation (Part 5) and Heal (Part 8) specs — included here so the
	// def is the single source of truth for it.
	Type AbilityType `json:"type,omitempty"`

	// ── Targeting ──────────────────────────────────────────────────────────
	// Whether the ability may target the caster itself / friendly units /
	// hostile units. Defaults are false; an ability authors the ones it needs.
	CanTargetSelf    bool `json:"canTargetSelf,omitempty"`
	CanTargetAllies  bool `json:"canTargetAllies,omitempty"`
	CanTargetEnemies bool `json:"canTargetEnemies,omitempty"`
	// TargetsPoint marks a GROUND/POINT-targeted ability (arcane_orb): the
	// player clicks a world location (ground or a unit's position) and the
	// ability fires toward that point rather than at a unit. Point casts route
	// through beginAbilityCastAtPointLocked. Mutually exclusive with the
	// CanTarget* unit flags in practice.
	TargetsPoint bool `json:"targetsPoint,omitempty"`

	// CastRange: number (world px) or "match_attack_range". See CastRange.
	CastRange CastRange `json:"castRange"`

	// ── Cost / timing ──────────────────────────────────────────────────────
	CastTime float64 `json:"castTime,omitempty"` // seconds the cast takes
	ManaCost int     `json:"manaCost,omitempty"` // default 0 (free)
	Cooldown float64 `json:"cooldown,omitempty"` // seconds, default 0

	// DamageType is the optional element/school of the ability (Part 2).
	// Empty = unspecified (resolves to physical via DamageType.OrPhysical()).
	// It ALSO doubles as the spell's "school" for the spell-modifier pipeline
	// (spell_modifier.go): a modifier targeting `{school: "fire"}` matches any
	// ability whose DamageType is "fire". There is deliberately no separate
	// School field — element and school are one concept here.
	DamageType DamageType `json:"damageType,omitempty"`

	// Tags are free-form authored classifiers (e.g. "aoe", "projectile",
	// "chain", "cc") used purely as targeting keys for the spell-modifier
	// pipeline — a modifier targeting `{tag: "aoe"}` applies to any ability
	// whose Tags contains "aoe". Absent ⇒ empty; a tag has NO effect on base
	// cast behaviour on its own. See spell_modifier.go.
	Tags []string `json:"tags,omitempty"`

	ByRank map[string][]AbilityRankOverride `json:"byRank,omitempty"`


	// Category classifies what the ability is for (heal / buff_ally / summon /
	// offensive). Optional; empty = unspecified. INERT in Phase 1 — populated
	// from JSON and validated at load (see init below) but read by no runtime
	// code yet; Phase 2 ability-priority scoring will branch on it. Mirrors the
	// DamageType extensible-enum pattern (see ability_category.go).
	Category AbilityCategory `json:"category,omitempty"`

	// HealAmount is the HP an effect-ability restores to its target on
	// resolve (Heal). NOTE: not in the Part 6 attribute list — added with the
	// Heal ability as the ability-specific effect magnitude. 0 ⇒ the ability
	// does not heal. Capped at the target's MaxHP (no overheal) at resolve.
	HealAmount int `json:"healAmount,omitempty"`

	// DamageAmount is the HP an offensive ability deals to its target on
	// resolve. Symmetric to HealAmount: 0 ⇒ the ability does no damage (the
	// field is additive and inert for every ability that omits it). Applied
	// through the shared authoritative damage pipeline
	// (applyUnitDamageWithSourceLocked) so mitigation, the death pipeline,
	// threat, and determinism are inherited — it is NOT a parallel damage
	// path. HealAmount and DamageAmount are independent resolve steps; an
	// ability may declare either, both, or neither.
	DamageAmount int `json:"damageAmount,omitempty"`

	// MinorDamage marks an ability's damage as "minor": it renders as a smaller
	// side-falling popup (colored by damage school) rather than the main
	// floating damage number. Used by rapid-fire, ancillary hits like Arcane
	// Missiles so a volley reads as spray, not one big number. 0/false ⇒ normal
	// major popup.
	MinorDamage bool `json:"minorDamage,omitempty"`

	// DamagePerSecond is the damage-over-time RATE (HP per second) an ability
	// applies while its effect persists, as opposed to DamageAmount's one-shot
	// hit. Used by the arcane_orb vortex, which deals DamagePerSecond to hostiles
	// in its radius on a fixed cadence as it travels. The field name is the
	// contract: authors set a per-second number, not a per-hit one. 0 ⇒ no DoT.
	// Modifier-eligible via the same `damage` SpellModField (a "+X% damage" perk
	// scales the DoT too); a spell uses either DamageAmount or DamagePerSecond,
	// never both, so they never collide under one modifier.
	DamagePerSecond float64 `json:"damagePerSecond,omitempty"`

	// TargetCount is the number of targets this ability can affect per cast.
	// Default (0 or absent) normalises to 1 (single-target). Values > 1 drive
	// the multi-target path: the resolver applies the effect to up to TargetCount
	// valid candidates ordered by ascending HP percent, tie-broken by unit.ID.
	// Loaded from JSON key "targetCount"; values < 1 are normalised to 1 at load.
	TargetCount int `json:"targetCount,omitempty"`

	// SummonUnitType is the unit-type id (matches a catalog/units/.../<id>.json)
	// that this ability spawns on resolve. Empty ⇒ ability is not a summon
	// (the field is inert for every existing ability, same pattern as
	// HealAmount / DamageAmount). The spawned unit takes the caster's OwnerID
	// and color and appears at a small fixed offset from the caster's
	// position (deterministic — no RNG). An unknown id is logged once at
	// resolve and the call is a no-op (mana was already spent), matching the
	// existing getProjectileDef miss handling.
	SummonUnitType string `json:"summonUnitType,omitempty"`

	// SummonCount is the number of units (of SummonUnitType) this ability
	// spawns per resolve. Default (0 or absent) normalises to 1. Values > 1
	// fan the spawns out in a deterministic horizontal row below the caster
	// so they do not stack at the same coordinate. Inert when
	// SummonUnitType is empty.
	SummonCount int `json:"summonCount,omitempty"`

	// ── Auto-cast ──────────────────────────────────────────────────────────
	// SupportsAutoCast gates whether the action bar exposes an auto-cast
	// toggle for this ability (default false). AutoCastTargetSelector names a
	// targeting strategy in the auto-cast selector registry (built in a later
	// part); it is just a string here — resolution/validation is the
	// registry's job.
	SupportsAutoCast       bool   `json:"supportsAutoCast,omitempty"`
	AutoCastTargetSelector string `json:"autoCastTargetSelector,omitempty"`
	// DefaultAutoCast controls whether the ability's auto-cast toggle starts
	// in the ENABLED state at unit spawn / ability grant. Only applies when
	// SupportsAutoCast is true. Player intent always overrides — once the
	// player toggles the ability (on or off), the explicit value is preserved
	// through promotions and ability replacements (heal → greater_heal). New
	// abilities granted at higher ranks default per this flag at grant time.
	// Player-owned units only — enemy units never get the default seeded.
	DefaultAutoCast bool `json:"defaultAutoCast,omitempty"`

	// ── Channeled-beam extension ───────────────────────────────────────────
	// ChannelType, when non-empty, routes the ability into the channel
	// lifecycle (ability_channel.go) instead of the standard one-shot cast.
	// The only supported value today is "beam" (Siphon Life). Empty or absent
	// = legacy one-shot cast; all existing abilities are unaffected.
	ChannelType string `json:"channelType,omitempty"`

	// TickIntervalSeconds is the cadence at which the channel's per-tick
	// effect fires (e.g. 0.25 = four times per second). Only meaningful when
	// ChannelType != "".
	TickIntervalSeconds float64 `json:"tickIntervalSeconds,omitempty"`

	// ManaCostPerTick is the mana deducted on each channel tick. The channel
	// stops when the caster cannot afford the next tick. Only meaningful when
	// ChannelType != "". The top-level ManaCost field is the per-CAST cost
	// (paid at channel start); these two are independent.
	ManaCostPerTick int `json:"manaCostPerTick,omitempty"`

	// DamagePerTick is the damage dealt to the channel target each tick.
	// Routed through applyUnitDamageWithSourceLocked. Only meaningful when
	// ChannelType != "".
	DamagePerTick int `json:"damagePerTick,omitempty"`

	// HealingMultiplier scales the damage-to-healing conversion for Siphon
	// Life. healAmount = round(DamagePerTick * HealingMultiplier). Default
	// 0.0 (zero) is normalised to 1.0 at load time so omitting the field
	// produces 1× conversion (lossless siphon). Only meaningful when
	// ChannelType != "".
	HealingMultiplier float64 `json:"healingMultiplier,omitempty"`

	// AllyHealRadius is the world-pixel radius within which the channel
	// looks for an ally to route excess healing to when the caster is at full
	// HP. 0 = no ally routing (self-only). Only meaningful when ChannelType != "".
	AllyHealRadius float64 `json:"allyHealRadius,omitempty"`

	// (Channel-pose frames live on the caster's UnitDef / PathDef — see
	// UnitDef.ChannelLoop and pathCatalogFile.ChannelLoop. They are visual
	// data about the caster's sprite, not the ability, so two units sharing
	// one channel ability can pin to different frames on their own sheets.)

	// ── Presentation / resolution hooks ────────────────────────────────────
	// Icon is the action-bar icon path. TODO(asset): real icon art.
	Icon string `json:"icon,omitempty"`
	// CasterAnimation is the animation status the caster plays while casting
	// (e.g. "Casting"). CasterAnimationOrCasting() defaults it.
	CasterAnimation string `json:"casterAnimation,omitempty"`
	// EffectOnTarget is the effect id (Part 4) played on the target when the
	// ability resolves (e.g. "healing_glow"). Empty = none. Resolved
	// fail-safe at use time (an unknown id just means "no effect").
	EffectOnTarget string `json:"effectOnTarget,omitempty"`

	// EffectAtPoint is a registered effect id (catalog/effects/<id>) played at
	// a POINT ability's cast LOCATION on resolve — the ground burst for an
	// instant point-AoE (Shatter). It is world-anchored (not tied to any unit),
	// so it plays even when the cast lands on empty ground with no enemies in
	// range. Empty ⇒ no ground effect. Resolved fail-safe (an unregistered id
	// just means "no effect"), same discipline as EffectOnTarget. Inert for
	// unit-target abilities.
	EffectAtPoint string `json:"effectAtPoint,omitempty"`
	// EffectScale multiplies the EffectAtPoint sprite's rendered size so the
	// burst can be matched to the spell's area radius (the effect art is a
	// fixed-size sheet). 0 / absent ⇒ 1× (the sheet's native size). Visual only.
	EffectScale float64 `json:"effectScale,omitempty"`
	// BurnEffectAtPoint is a SECOND, looping ground effect played at the impact
	// point for the burn duration (in addition to EffectAtPoint's fall/impact
	// animation) — e.g. Meteor's smoldering crater. Queued by the GroundHazard at
	// impact (not at cast) and sized with EffectScale so it lines up with the
	// meteor's own impact frames. Empty ⇒ no lingering VFX. Visual only.
	BurnEffectAtPoint string `json:"burnEffectAtPoint,omitempty"`

	// Projectile is the optional projectile-def id (catalog/projectiles/<id>)
	// an offensive ability launches at its target on resolve. When set (and
	// DamageAmount > 0) the ability's damage is DEFERRED and delivered by a
	// homing bolt that travels to the target and applies the damage on impact —
	// the same pipeline basic-attack shots use — instead of being applied
	// instantly. Empty ⇒ instant (hitscan) damage, the prior behaviour. Inert
	// for abilities with no DamageAmount.
	Projectile string `json:"projectile,omitempty"`

	// ── Spell mechanic parameters (arch-mage-spell-system) ─────────────────
	// These are additive, inert-when-zero knobs read by the specific spell
	// mechanics that need them (fireball splash, chain_lightning bounce,
	// arcane_orb pull). Each is also a base value the spell-modifier pipeline
	// (spell_modifier.go) can resolve an effective value from at cast time —
	// see EffectiveSpell and the SpellModField enum. Omitting a field leaves it
	// 0 and inert for every ability that does not use it (same discipline as
	// HealAmount / DamageAmount / the channel fields above).

	// Radius is the world-pixel radius of an ability's area effect: fireball's
	// splash radius, arcane_orb's pull radius. 0 ⇒ single-target / no area.
	Radius float64 `json:"radius,omitempty"`
	// ProjectileSpeed optionally overrides the launched projectile's speed for
	// modifier purposes. 0 ⇒ use the projectile def's own speed.
	ProjectileSpeed float64 `json:"projectileSpeed,omitempty"`
	// ProjectileScale multiplies the caster's projectile render size for this
	// ability's bolts (e.g. 0.5 ⇒ arcane_missiles render at half the caster's
	// scale). 0/absent ⇒ 1× (use the caster's scale unchanged). Visual only.
	ProjectileScale float64 `json:"projectileScale,omitempty"`
	// Duration is how long a timed effect this ability applies lasts, in
	// seconds (arcane_orb's pull duration). 0 ⇒ no timed effect.
	Duration float64 `json:"duration,omitempty"`
	// ChainCount is the number of extra targets a chaining ability arcs to
	// after the primary (chain_lightning). Maps to the bounce mechanic's
	// bounceCount. 0 ⇒ no chaining.
	ChainCount int `json:"chainCount,omitempty"`
	// BounceRange is the max world-pixel leap distance between chain hops.
	// Read directly by the chain mechanic; NOT modifier-eligible. 0 ⇒ mechanic
	// default. Inert unless ChainCount > 0.
	BounceRange float64 `json:"bounceRange,omitempty"`
	// BounceDamageFalloff is the flat damage lost per chain hop. Read directly
	// by the chain mechanic; NOT modifier-eligible. Inert unless ChainCount > 0.
	BounceDamageFalloff int `json:"bounceDamageFalloff,omitempty"`
	// PullStrength is the forced-displacement pull rate (world px per second)
	// applied by a pulling ability (arcane_orb). 0 ⇒ no pull. Modifier-eligible.
	PullStrength float64 `json:"pullStrength,omitempty"`

	// SlowMultiplier / SlowDurationSeconds declare an on-hit SLOW an ability
	// stamps on every enemy it damages (Shatter's chill). They are routed
	// through the shared proc-slow seam (applyProcSlowLocked) by the ability's
	// DamageType: a "cold" ability lands the Chilled cold-slow track (icy
	// overlay + reduced move AND attack speed), any other school lands the
	// physical/generic slow track — so no ability re-implements slowing logic.
	// SlowMultiplier is the speed fraction (e.g. 0.5 ⇒ 50% speed); a value not
	// in (0,1) is inert (slowTargetLocked rejects it). SlowDurationSeconds is
	// how long it lasts. Both 0 / absent ⇒ the ability applies no slow (inert
	// for every ability that omits them). Read directly off the def — NOT
	// modifier-eligible today (same discipline as BounceRange).
	SlowMultiplier      float64 `json:"slowMultiplier,omitempty"`
	SlowDurationSeconds float64 `json:"slowDurationSeconds,omitempty"`

	// ── Delayed-impact ground hazard (Meteor and future "sky-drop" spells) ──────
	// These drive the generic GroundHazard entity (ground_hazard.go), spawned by
	// resolveAbilityCastAtPointLocked when ImpactDelaySeconds > 0. Impact damage
	// reuses DamageAmount; impact radius reuses Radius. Any future delayed-AoE +
	// lingering-DoT spell reuses these without new code.
	//
	// ImpactDelaySeconds is the "fall time": seconds between cast resolution and
	// the one-time impact AoE. Keep it ≈ effectDuration × (impactFrame-1)/frames
	// so the falling sprite lands when damage lands (see the meteor effect).
	// omitempty is deliberate here (unlike CastRange, which is always-present
	// cast-setup data): these are inert-when-zero mechanic knobs, so a def
	// that doesn't use them (every ability except Meteor, as of this writing)
	// should not carry a page of zombie "0" fields on disk. Zero unmarshals
	// identically whether the key is present or absent, so this is a pure
	// on-disk-cleanliness change with no behavior difference.
	ImpactDelaySeconds float64 `json:"impactDelaySeconds,omitempty"`
	// Burn (lingering ground zone) knobs. Active only when BurnDurationSeconds > 0.
	BurnDurationSeconds     float64 `json:"burnDurationSeconds,omitempty"`
	BurnDamagePerTick       int     `json:"burnDamagePerTick,omitempty"`
	BurnTickIntervalSeconds float64 `json:"burnTickIntervalSeconds,omitempty"`
	BurnRadius              float64 `json:"burnRadius,omitempty"`

	// ── Passive charge-fire (arcane_missiles) ──────────────────────────────
	// When Type == AbilityPassive and ChargeRequired > 0 this is an auto-firing
	// passive: the owning unit accumulates Arcane Charge as it spends mana
	// (ManaToChargeRatio charge per mana point) and, once charge reaches
	// ChargeRequired, automatically fires MissileCount projectiles at random
	// in-range enemies (DamagePerMissile each), then resets charge. Never
	// manually/auto cast. All fields configurable; see spell_charge.go.
	//
	// These fields are cleared to zero on a converted (SchemaVersion>=2) def
	// (ConvertLegacyAbility) — the compiled Program's charge_fire_volley
	// action config is the sole authority for a migrated ability. Every
	// runtime reader goes through chargeFireSpecFor (spell_charge.go), never
	// these fields directly, so it works either way.
	ChargeRequired        float64 `json:"chargeRequired,omitempty"`
	ManaToChargeRatio     float64 `json:"manaToChargeRatio,omitempty"` // 0 ⇒ normalised to 1.0 at load for a charge-fire passive
	MissileCount          int     `json:"missileCount,omitempty"`
	DamagePerMissile      int     `json:"damagePerMissile,omitempty"`
	Targeting             string  `json:"targeting,omitempty"` // e.g. "random_enemy_in_range"
	AllowDuplicateTargets bool    `json:"allowDuplicateTargets,omitempty"`
	// MissileDelayMs is the delay in MILLISECONDS between successive bolts of one
	// volley (the rat-a-tat stagger). 0/absent ⇒ the default
	// (arcaneMissileStaggerSeconds). Authored in ms for readability; the roller
	// converts to seconds.
	MissileDelayMs float64 `json:"missileDelayMs,omitempty"`

	// ── Composable program (schema v2) ─────────────────────────────────────
	// SchemaVersion selects which representation is authoritative. Absent/1 ⇒
	// the legacy flat mechanic fields above drive runtime and Program is nil
	// (or compiled transiently elsewhere). 2 ⇒ Program is the authoritative
	// behavior and the legacy mechanic fields are dropped on conversion. The
	// two never coexist as competing values for the same ability.
	SchemaVersion int `json:"schemaVersion,omitempty"`
	// Program is the composable trigger/action behavior for a schema-v2 ability.
	// Nil for legacy abilities. Validated by validateAbilityProgram via the
	// shared validateAbilityDef gate; not executed in this phase.
	Program *AbilityProgram `json:"program,omitempty"`
}

// IsPassive reports whether this ability is a passive (never manually or
// auto-cast, never on the castable action row).
func (a AbilityDef) IsPassive() bool { return a.Type == AbilityPassive }

// IsChargeFirePassive reports whether this ability is an Arcane-Charge-driven
// auto-firing passive (arcane_missiles): a passive with a positive charge
// threshold.
//
// A converted (SchemaVersion>=2) charge-fire ability has ChargeRequired
// cleared to 0 by ConvertLegacyAbility, so the flat-field check alone would
// go permanently false the moment arcane_missiles migrates — silently
// breaking BOTH this method's own callers (spell_charge.go's
// unitChargeFirePassiveLocked used to call it directly; the Arch Mage Gold
// perk gate in projectile.go's landProjectileLocked still does) AND anything
// that assumes IsPassive()+charge-fire implies the charge loop is live. The
// second branch below anchors on the Program's own SHAPE instead (does it
// have an on_charge_full trigger with a charge_fire_volley action?) — a
// cheap, direct, honest check that survives migration without needing a full
// abilityMechanicsShadow reconstruction on every call (this is checked on
// hot per-hit / per-mana-spend paths).
func (a AbilityDef) IsChargeFirePassive() bool {
	if a.IsPassive() && a.ChargeRequired > 0 {
		return true
	}
	if a.SchemaVersion >= 2 && a.Program != nil {
		_, ok := findChargeFireVolleyConfig(a.Program)
		return ok
	}
	return false
}

// IsChannelAbility reports whether this ability is a channeled beam
// (siphon_life): a per-tick drain/heal loop driven by ability_channel.go
// instead of a normal one-shot cast.
//
// A converted (SchemaVersion>=2) channel ability has ChannelType cleared to
// "" by ConvertLegacyAbility, so the flat-field check alone would go
// permanently false the moment siphon_life migrates — silently breaking
// every caller that gates on "is this a channel?" (beginAbilityCastLocked's
// dispatch into the channel lifecycle, the auto-cast preconditions in
// ability_autocast.go, describeLegacyAbility's prose dispatch). This is
// exactly IsChargeFirePassive's fix, re-applied here: channelSpecFor's
// second branch anchors on the Program's own SHAPE instead (does it have an
// on_cast_complete channel_beam action?) — see that function's doc comment
// (ability_channel.go).
func (a AbilityDef) IsChannelAbility() bool {
	_, ok := channelSpecFor(a)
	return ok
}

// HasTag reports whether this ability declares the given tag. Used by the
// spell-modifier pipeline's tag-targeted matching (spell_modifier.go). Empty
// tag never matches (an empty target field is a wildcard handled by the
// matcher, not by this method).
func (a AbilityDef) HasTag(tag string) bool {
	if tag == "" {
		return false
	}
	for _, t := range a.Tags {
		if t == tag {
			return true
		}
	}
	return false
}

// CasterAnimationOrCasting returns the caster animation status, defaulting an
// unset value to the canonical "Casting" slot (unit_animation.go).
func (a AbilityDef) CasterAnimationOrCasting() string {
	if a.CasterAnimation == "" {
		return unitStatusCasting
	}
	return a.CasterAnimation
}

// EffectiveCooldown returns the cooldown duration the UI should display and
// the cooldown system should arm on each cast. It is max(Cooldown, CastTime)
// so the action-bar clock-wipe overlay is always visible while the cast is
// in flight — without this clamp, a 1s-cast / 0s-cooldown spell (base Heal)
// would have NO visible wipe even though the unit is locked in place
// casting for a full second, leaving the player wondering whether their
// click registered. When Cooldown >= CastTime (Greater Heal: 3s cd vs 1s
// cast) the cooldown drives the wipe as authored. Cast time alone is never
// shorter than what the unit is committed to anyway, so this lower bound
// adds no false "still on cooldown" gating.
func (a AbilityDef) EffectiveCooldown() float64 {
	if a.CastTime > a.Cooldown {
		return a.CastTime
	}
	return a.Cooldown
}

// canAbilityTargetUnitLocked reports whether target is a legal target for
// ability `a` cast by caster, per the self / ally / enemy permission flags.
// A nil or dead target is never valid. Classification: same unit = self;
// same TEAM = ally (via unitsFriendlyLocked — alliance is data, Player.TeamID,
// not ownership); otherwise = enemy. At the default single team this is
// identical to the old same-OwnerID rule. (Range is a separate check —
// see WithinCastRange.)
//
// Caller holds s.mu.
func (s *GameState) canAbilityTargetUnitLocked(a AbilityDef, caster, target *Unit) bool {
	if caster == nil || target == nil || target.HP <= 0 {
		return false
	}
	switch {
	case target.ID == caster.ID:
		return a.CanTargetSelf
	case s.unitsFriendlyLocked(caster, target):
		return a.CanTargetAllies
	default:
		// Point-targeted offensive abilities (arcane_orb) don't target a unit
		// when cast, but auto-cast selection still needs to "see" enemies to
		// aim the point at one — so treat enemies as valid candidates here.
		return a.CanTargetEnemies || a.TargetsPoint
	}
}

// WithinCastRange reports whether target is within this ability's cast range
// of caster (cast range resolved against the caster for the
// match_attack_range case). A non-positive resolved range can never reach a
// distinct target; a unit targeting itself is always within range.
func (a AbilityDef) WithinCastRange(caster, target *Unit) bool {
	return a.WithinCastRangeScaled(caster, target, 1.0)
}

// WithinCastRangeScaled is WithinCastRange with the resolved range
// multiplied by `mult` first. Used by perks that scale a specific channel
// ability's reach (e.g. beam_mastery on Siphon Life). Pass 1.0 for the
// default behaviour. A non-positive `mult` collapses the range to 0,
// matching the "ability can't reach anything" semantic of CastRange == 0.
func (a AbilityDef) WithinCastRangeScaled(caster, target *Unit, mult float64) bool {
	if caster == nil || target == nil {
		return false
	}
	if target.ID == caster.ID {
		return true // distance 0 — self is always in range
	}
	r := a.CastRange.Resolve(caster) * mult
	if r <= 0 {
		return false
	}
	return distanceSquared(caster.X, caster.Y, target.X, target.Y) <= r*r
}

// validateAbilityDef checks an ability def's content and normalizes its
// defaultable numeric fields IN PLACE. It is the single validation gate shared
// by the catalog loader (loadAbilityDefs) and the editor save path
// (SaveAbilityDef), so a def that loads cleanly is exactly a def that saves
// cleanly. It deliberately does NOT check the id — the loader gates that
// against the directory name and the editor against abilityIDPattern.
func validateAbilityDef(def *AbilityDef) error {
	if def.DamageType != "" && !IsValidDamageType(def.DamageType) {
		return fmt.Errorf("damageType %q is not a registered damage type", def.DamageType)
	}
	if def.Category != "" && !IsValidAbilityCategory(def.Category) {
		return fmt.Errorf("category %q is not a registered ability category", def.Category)
	}
	// A burn is carried by the ground hazard spawned at impact (see
	// ground_hazard.go); with no impact delay there is no hazard to carry the
	// burn, so a configured burn requires a positive impact delay.
	if def.BurnDurationSeconds > 0 && def.ImpactDelaySeconds <= 0 {
		return fmt.Errorf("burnDurationSeconds requires impactDelaySeconds > 0")
	}
	// A zero (or negative) tick interval would make tickGroundHazardsLocked
	// advance its tick timer by 0 each call and loop forever, so a configured
	// burn requires a positive tick interval.
	if def.BurnDurationSeconds > 0 && def.BurnTickIntervalSeconds <= 0 {
		return fmt.Errorf("burnDurationSeconds requires burnTickIntervalSeconds > 0")
	}
	if def.TargetCount < 1 {
		def.TargetCount = 1
	}
	// EXCEPTION to "mechanic fields stay cleared on a v2 def": TargetCount is
	// backfilled (once, here, at load/save time — never per-cast) from the
	// compiled Program when the authored def didn't set it. Every OTHER
	// consumer of a v2 ability's TargetCount already gets the right answer
	// without this: resolveAbilityCastLocked's SchemaVersion>=2 branch reads
	// only targets[0] and lets the Program's own select_targets query do the
	// real multi-target fan-out (see ability_legacy_fixtures_test.go's
	// ANCHOR-COLLAPSE note), and describeAbility already recovers the number
	// for tooltip prose via abilityMechanicsShadow. But
	// protocol.AbilitySnapshot.TargetCount (abilityStatesLocked,
	// ability_autocast.go) reads def.TargetCount directly as wire display
	// metadata — with no backfill it would report 1 for a 3-target heal like
	// greater_heal, silently telling the client "single target" for an
	// ability that heals three. Recovering it here (once, at load) instead of
	// on every snapshot build keeps the hot per-tick snapshot path
	// allocation-free (AI_RULES) while keeping the wire contract honest.
	if def.SchemaVersion >= 2 && def.Program != nil {
		if recovered := abilityMechanicsShadow(*def).TargetCount; recovered > def.TargetCount {
			def.TargetCount = recovered
		}
	}
	if def.SummonCount < 1 {
		def.SummonCount = 1
	}
	if def.ChannelType != "" && def.HealingMultiplier == 0 {
		def.HealingMultiplier = 1.0
	}
	// Legacy-only: a converted (SchemaVersion>=2) charge-fire ability's
	// ManaToChargeRatio lives in its compiled Program's charge_fire_volley
	// config (baked at conversion time from the already-normalized legacy
	// value), not on the flat field — writing 1.0 onto the raw def here would
	// silently violate the "mechanic fields stay cleared on a v2 def"
	// contract every other migrated ability upholds.
	if def.SchemaVersion < 2 && def.IsChargeFirePassive() && def.ManaToChargeRatio == 0 {
		def.ManaToChargeRatio = 1.0
	}
	// SchemaVersion and Program must agree: SchemaVersion>=2 is a contract
	// that Program is the sole behavioral authority (legacy mechanic fields
	// are cleared on conversion — see ConvertLegacyAbility), and a non-nil
	// Program is only ever meaningful under that contract. Letting the two
	// drift apart is a silent trap: resolveAbilityCastLocked's routing gate
	// checks BOTH (`SchemaVersion >= 2 && Program != nil`), so a half-edited
	// def (e.g. schemaVersion bumped but program never authored, or a program
	// authored but schemaVersion left at 0) would silently fall through to
	// the legacy per-field path — with cleared mechanic fields in the first
	// case (an inert ability) or stale legacy fields racing an ignored
	// Program in the second. Fail loudly at load/save instead.
	if def.SchemaVersion >= 2 && def.Program == nil {
		return fmt.Errorf("schemaVersion %d requires a program (composable abilities must set both)", def.SchemaVersion)
	}
	if def.Program != nil && def.SchemaVersion < 2 {
		return fmt.Errorf("program is set but schemaVersion is %d (composable abilities must set schemaVersion >= 2)", def.SchemaVersion)
	}
	if err := validateAbilityRankOverrides(*def); err != nil {
		return err
	}
	if def.Program != nil {
		for _, issue := range validateAbilityProgram(def.Program) {
			if issue.Severity == "error" {
				if issue.Path != "" {
					return fmt.Errorf("program invalid at %s: %s", issue.Path, issue.Message)
				}
				return fmt.Errorf("program invalid: %s", issue.Message)
			}
		}
	}
	return nil
}

// abilityDefsByID is a package-level var, initialized before any init() that
// might reference ability defs (same rationale as the other catalogs).
var abilityDefsByID = loadAbilityDefs()

func loadAbilityDefs() map[string]AbilityDef {
	entries, err := fs.ReadDir(abilityDefsFS, "catalog/abilities")
	if err != nil {
		panic("catalog/abilities: " + err.Error())
	}
	result := make(map[string]AbilityDef, len(entries))
	for _, entry := range entries {
		// Skip non-directory entries (e.g. the .keep placeholder). Abilities
		// must live at catalog/abilities/<id>/<id>.json.
		if !entry.IsDir() {
			continue
		}
		idKey := entry.Name()
		rel := "catalog/abilities/" + idKey + "/" + idKey + ".json"
		data, err := abilityDefsFS.ReadFile(rel)
		if err != nil {
			panic(rel + ": " + err.Error())
		}
		var def AbilityDef
		if err := json.Unmarshal(data, &def); err != nil {
			panic(rel + ": " + err.Error())
		}
		if def.ID == "" {
			panic(rel + `: missing "id" field`)
		}
		if def.ID != idKey {
			panic(rel + ": def.ID " + def.ID + " does not match directory name " + idKey)
		}
		if err := validateAbilityDef(&def); err != nil {
			panic(rel + ": " + err.Error())
		}
		if _, dup := result[def.ID]; dup {
			panic(rel + `: duplicate ability id "` + def.ID + `"`)
		}
		result[def.ID] = def
	}
	return result
}

// getAbilityDef looks up an ability definition by id, overlay-first (an
// authored override wins over the embedded default), then the embedded
// catalog. The bool is false when no ability with that id is registered.
func getAbilityDef(id string) (AbilityDef, bool) {
	runtimeAbilitiesMu.RLock()
	if def, ok := runtimeAbilities[id]; ok {
		runtimeAbilitiesMu.RUnlock()
		return def, true
	}
	runtimeAbilitiesMu.RUnlock()
	def, ok := abilityDefsByID[id]
	return def, ok
}

// ListAbilityDefs returns every registered ability definition (overlay merged
// over embed) sorted by id.
func ListAbilityDefs() []AbilityDef {
	merged := make(map[string]AbilityDef, len(abilityDefsByID))
	for id, def := range abilityDefsByID {
		merged[id] = def
	}
	runtimeAbilitiesMu.RLock()
	for id, def := range runtimeAbilities {
		merged[id] = def
	}
	runtimeAbilitiesMu.RUnlock()
	defs := make([]AbilityDef, 0, len(merged))
	for _, def := range merged {
		defs = append(defs, def)
	}
	sort.Slice(defs, func(i, j int) bool { return defs[i].ID < defs[j].ID })
	return defs
}
