root = "."
tmp_dir = "tmp"

[build]
  cmd = "C:\\Users\\Chad Anderson\\web-rts-nomads\\server\\build.bat"
  entrypoint = "./tmp/api.exe"
  include_ext = ["go", "json"]
  include_dir = ["cmd", "internal", "pkg"]
  exclude_dir = ["tmp"]
  delay = 500
  shell = ["cmd", "/c"]

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
