import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { PNG } from 'pngjs'
import { describe, expect, it } from 'vitest'
import {
  animSlugFromHashedName, DIRECTION_ORDER, normalizeExportShape, planSpriteSheets,
} from './spritePacking'

describe('pure helpers', () => {
  it('slug is the pre-dash segment, lowercased', () => {
    expect(animSlugFromHashedName('Walking-1656a518')).toBe('walking')
    expect(animSlugFromHashedName('Attacking')).toBe('attacking')
  })
  it('normalizeExportShape unwraps states[0] only when frames is absent', () => {
    expect(normalizeExportShape({ states: [{ frames: { rotations: {} } }] })).toEqual({ frames: { rotations: {} } })
    const flat = { frames: { rotations: {} } }
    expect(normalizeExportShape(flat)).toBe(flat)
  })
  it('DIRECTION_ORDER is cardinals-first', () => {
    expect(DIRECTION_ORDER.slice(0, 4)).toEqual(['north', 'south', 'east', 'west'])
  })
})

describe('planSpriteSheets layout', () => {
  const dims = (w: number, h: number) => ({ w, h })

  it('animation sheet is frames-wide by directions-tall, rowOrder cardinals first', () => {
    const meta = {
      character: { size: { width: 8, height: 8 } },
      frames: { rotations: {}, animations: { 'Walking-abc': { north: ['a0', 'a1'], south: ['b0', 'b1'] } } },
    }
    const frameDims = { a0: dims(8, 8), a1: dims(8, 8), b0: dims(8, 8), b1: dims(8, 8) }
    const plan = planSpriteSheets(meta, frameDims)
    const walking = plan.manifest.animations!.walking
    expect(walking.frameCount).toBe(2)
    expect(walking.rowOrder).toEqual(['north', 'south'])
    const sheet = plan.sheets.find((s) => s.name === 'packed/walking.png')!
    expect(sheet.width).toBe(16)
    expect(sheet.height).toBe(16)
    expect(sheet.blits).toContainEqual({ srcKey: 'b1', dstX: 8, dstY: 8, w: 8, h: 8 })
  })

  it('a direction with fewer frames leaves trailing columns unblitted (no padding)', () => {
    const meta = {
      character: { size: { width: 4, height: 4 } },
      frames: { rotations: {}, animations: { 'Cast-x': { north: ['n0', 'n1', 'n2'], south: ['s0'] } } },
    }
    const frameDims = { n0: dims(4, 4), n1: dims(4, 4), n2: dims(4, 4), s0: dims(4, 4) }
    const plan = planSpriteSheets(meta, frameDims)
    const sheet = plan.sheets.find((s) => s.name === 'packed/cast.png')!
    expect(sheet.width).toBe(12)
    const southBlits = sheet.blits.filter((b) => b.dstY === 4)
    expect(southBlits).toHaveLength(1)
    expect(southBlits[0]).toMatchObject({ dstX: 0 })
  })

  it('rotations sheet is a 1-column vertical strip', () => {
    const meta = {
      character: { size: { width: 4, height: 4 } },
      frames: { rotations: { north: 'rn', south: 'rs' }, animations: {} },
    }
    const plan = planSpriteSheets(meta, { rn: dims(4, 4), rs: dims(4, 4) })
    expect(plan.manifest.rotations).toMatchObject({ sheet: 'packed/rotations.png', rowOrder: ['north', 'south'], frameWidth: 4, frameHeight: 4 })
    const sheet = plan.sheets.find((s) => s.name === 'packed/rotations.png')!
    expect(sheet.width).toBe(4)
    expect(sheet.height).toBe(8)
    expect(sheet.blits).toContainEqual({ srcKey: 'rs', dstX: 0, dstY: 4, w: 4, h: 4 })
  })

  it('throws on a frame-size mismatch (the CLI does)', () => {
    const meta = { character: { size: { width: 4, height: 4 } }, frames: { rotations: {}, animations: { 'Walk-x': { north: ['n0', 'n1'] } } } }
    expect(() => planSpriteSheets(meta, { n0: dims(4, 4), n1: dims(4, 5) })).toThrow(/mismatch/i)
  })
})

// ─── Golden conformance with the real CLI packer ───────────────────────────
// The fixture under __fixtures__/pack/ was generated by actually running
// `npm run pack:sprites` (see the fixture's README.md for the regen recipe)
// against a synthetic PixelLab-shaped export, then copying its output here.
// This proves the pure TS core reproduces the CLI's sheet math byte-for-byte
// — not just "shaped like it," but pixel-identical and manifest-identical.

// happy-dom's global URL/location shims interfere with `new URL(rel, import.meta.url)`
// resolution (truncates the path), so resolve via node:path against this
// file's own directory instead — robust regardless of the test environment.
const testFileDir = path.dirname(fileURLToPath(import.meta.url))
const fixture = (rel: string) => path.join(testFileDir, '__fixtures__', 'pack', rel)

// eslint-disable-next-line @typescript-eslint/no-explicit-any -- metadata.json is untyped JSON at the fixture boundary
function collectFramePaths(meta: any): string[] {
  const out: string[] = []
  for (const rel of Object.values(meta.frames?.rotations ?? {})) if (typeof rel === 'string') out.push(rel)
  for (const byDir of Object.values(meta.frames?.animations ?? {})) {
    for (const rels of Object.values((byDir ?? {}) as Record<string, string[]>)) {
      if (Array.isArray(rels)) out.push(...rels)
    }
  }
  return out
}

// Rasterizes a SheetPlan into a zero-init PNG by copying each blit's source
// rows — the same copy loop the CLI uses — so this is pngjs-vs-pngjs, apples
// to apples, and isolates the comparison to the TS core's layout math.
function rasterize(
  sheet: { width: number; height: number; blits: { srcKey: string; dstX: number; dstY: number; w: number; h: number }[] },
  frames: Record<string, InstanceType<typeof PNG>>,
): InstanceType<typeof PNG> {
  const out = new PNG({ width: sheet.width, height: sheet.height }) // zero-init = transparent
  for (const b of sheet.blits) {
    const src = frames[b.srcKey]
    for (let y = 0; y < b.h; y++) {
      const srcStart = y * src.width * 4
      const dstStart = ((b.dstY + y) * out.width + b.dstX) * 4
      src.data.copy(out.data, dstStart, srcStart, srcStart + b.w * 4)
    }
  }
  return out
}

describe('conformance with the CLI packer (golden fixture)', () => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- metadata.json is untyped JSON at the fixture boundary
  const meta: any = JSON.parse(readFileSync(fixture('metadata.json'), 'utf8'))
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- sprites.json is untyped JSON at the fixture boundary
  const golden: any = JSON.parse(readFileSync(fixture('sprites.json'), 'utf8'))

  const frameDims: Record<string, { w: number; h: number }> = {}
  const framePixels: Record<string, InstanceType<typeof PNG>> = {}
  for (const rel of collectFramePaths(meta)) {
    const png = PNG.sync.read(readFileSync(fixture(rel)))
    frameDims[rel] = { w: png.width, h: png.height }
    framePixels[rel] = png
  }

  const plan = planSpriteSheets(normalizeExportShape(meta), frameDims)

  it('manifest matches the CLI output (ignoring packedAt and the directory-derived key)', () => {
    // `packedAt` is a timestamp the core deliberately omits (caller/server
    // owns timestamps). `key` is `path.basename(unitDir)` in the CLI — pure
    // directory context planSpriteSheets never receives (see README.md in
    // this fixture dir and the SpriteManifestJSON doc comment) — a future
    // drop-zone task attaches it from the dropped folder's name.
    const { packedAt: _drop, key: _dropKey, ...goldenNoTsNoKey } = golden
    expect(plan.manifest).toEqual(goldenNoTsNoKey)
  })

  it('every sheet decodes to the same RGBA pixels as the CLI sheet', () => {
    for (const sheet of plan.sheets) {
      const ours = rasterize(sheet, framePixels)
      const cli = PNG.sync.read(readFileSync(fixture(sheet.name)))
      expect(ours.width).toBe(cli.width)
      expect(ours.height).toBe(cli.height)
      expect(Buffer.compare(ours.data, cli.data)).toBe(0)
    }
  })
})
